import React from 'react'
import styles from './Home.module.css'
import { Link } from 'react-router-dom'

const Home = () => {
  return (
      <div className={styles.home}>
          <h1 className='h1'>GUESS THE NUMBER</h1>
          <div className={styles.ins}>
            <div className="instructions">
              <p>Instructions - </p>
            </div>
            <div className={styles.steps}>
              <ul>
                <li>A random numer will be generated by the computer.</li>
                <li>The number will lie between 1-99 (both included).</li>
                <li>Try guessing the number in minimum attempts.</li>
                <li>After every guess you will be told if the guessed number is higher or lower than the generated number.</li>
              </ul>
            </div>
          </div>
          <div className={styles.play}>
            <Link to='/game'>
              <button className={styles.btn}>Play</button>
            </Link>
          </div>
          <div className={styles.play}>
            <Link to='/easy'>
              <button className={styles.btn}>Hard Mode</button>
            </Link>
          </div>

      </div>
  )
}

export default Home